
# **1. LIBRERIAS**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil

from sklearn.model_selection import train_test_split


import os, sys, math, gc, warnings
warnings.filterwarnings("ignore")


# **2. CONFIGURACIÓN DEL AMBIENTE**

## 2.1 VARIABLES GLOBALES

In [ ]:
# Semilla global para reproducibilidad
SEED = 42

# Le indicamos a Pandas que siempre muestre hasta 50 columnas completas en lugar de cortarlas con “...”.
pd.set_option("display.max_columns", 50)

## 2.2 ACCESO A DATOS

In [ ]:
# ---- Switch de entorno: "colab" o "local"
RUN_ENV = "colab"   # <-- cambia a "local" si no usas Google Colab

# ---- Rutas base
if RUN_ENV.lower() == "colab":
    try:
        from google.colab import drive
        drive.mount("/drive")
    except Exception as e:
        print("Aviso: no se pudo montar Drive automáticamente:", e)
    # Ajusta esta ruta a tu carpeta del proyecto en Drive
    BASE_DIR = "/drive/My Drive/Colab Notebooks/reto-Thales/"
else:
    # Ajusta a tu ruta local del proyecto
    BASE_DIR = "/path-de-computador-local/"

os.makedirs(BASE_DIR, exist_ok=True)

# Ruta del CSV principal (ajústala)
DATA_PATH = os.path.join(BASE_DIR, "data", "delitos_cdmx_sample_final_5percent.csv")


print(f"Entorno: {RUN_ENV} | BASE_DIR: {BASE_DIR}")
print(f"Archivo de datos: {DATA_PATH}")

Mounted at /drive
Entorno: colab | BASE_DIR: /drive/My Drive/Colab Notebooks/reto-Thales/
Archivo de datos: /drive/My Drive/Colab Notebooks/reto-Thales/data/delitos_cdmx_sample_final_5percent.csv

## 2.3 ACCESO A FUNCIONES UTILITÁRIAS

In [ ]:
# Vamos utilizar un archivo de funciones propio
sys.path.insert(0, BASE_DIR) #para acceder desde Colab-Drive
import myUtils as myUtils


# **3. LECTURA DE DATOS**

In [ ]:
df = pd.read_csv(DATA_PATH, low_memory=False)
print(f'Tamanio del dataset: {df.shape}')

Tamanio del dataset: (209873, 21)

In [ ]:
df

,anio_inicio,mes_inicio,fecha_inicio,hora_inicio,anio_hecho,mes_hecho,fecha_hecho,hora_hecho,delito,competencia,fiscalia,agencia,unidad_investigacion,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho,latitud,longitud,categoria_delito
0,2016,Mayo,2016-05-10,00:00:00,2016.0,Abril,2016-04-03,12:28:00,AMENAZAS,NaN,INVESTIGACIÓN EN COYOACÁN,COY-1,UI-1CD,CULHUACÁN CTM SECCIÓN V,Culhuacan Ctm Seccion I,COYOACAN,NaN,CDMX,19.331820,-99.118620,delito de bajo impacto
1,2016,Mayo,2016-05-18,00:00:00,2016.0,Mayo,2016-05-18,15:10:00,LESIONES CULPOSAS POR TRANSITO VEHICULAR EN CO...,NaN,INVESTIGACIÓN EN CUAUHTEMOC,CUH-2,UI-3CD,DOCTORES,Doctores,CUAUHTEMOC,NaN,CDMX,19.424800,-99.142540,delito de bajo impacto
2,2016,Julio,2016-07-07,00:00:00,2016.0,Mayo,2016-05-16,02:00:00,ROBO DE OBJETOS,NaN,INVESTIGACIÓN EN CUAUHTEMOC,CUH-2,UI-2SD,SANTA MARIA LA RIBERA,Santa Maria La Ribera,CUAUHTEMOC,NaN,CDMX,19.443370,-99.158010,delito de bajo impacto
3,2016,Enero,2016-01-04,00:00:00,2016.0,Enero,2016-01-04,15:30:00,PERDIDA DE LA VIDA POR OTRAS CAUSAS,NaN,INVESTIGACIÓN EN CUAUHTEMOC,CUH-8,UI-3CD,ESPERANZA,Esperanza,CUAUHTEMOC,NaN,CDMX,19.421770,-99.126740,hecho no delictivo
4,2016,Febrero,2016-02-08,00:00:00,2016.0,Febrero,2016-02-01,14:00:00,VIOLENCIA FAMILIAR,NaN,INVESTIGACIÓN EN XOCHIMILCO,XO-2,UI-2SD,LA JOYA,NaN,XOCHIMILCO,NaN,CDMX,19.231226,-99.095951,delito de bajo impacto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209868,2025,Enero,2025-01-31 16:25:45,16:25:45:00,2025.0,Enero,2025-01-31 14:00:00,14:00:00:00,VIOLENCIA FAMILIAR,FUERO COMUN,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN TLALPAN,UAT-TLP-5,UI-1SD,PEDREGAL DE AMINCO,Pueblo San Francisco Tlalnepantla,TLALPAN,NaN,CDMX,19.201846,-99.131102,delito de bajo impacto
209869,2025,Enero,2025-01-02 17:56:48,17:56:48:00,2025.0,Enero,2025-01-02 14:58:00,14:58:00:00,VIOLENCIA FAMILIAR,FUERO COMUN,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN TLALPAN,TLP-3,UI-1CD,SAN MIGUEL TOPILEJO,Pueblo San Miguel Topilejo,TLALPAN,NaN,CDMX,19.191853,-99.141353,delito de bajo impacto
209870,2025,Enero,2025-01-06 02:13:04,02:13:04:00,2024.0,Diciembre,2024-12-17 06:00:00,06:00:00:00,ROBO A PASAJERO A BORDO DE METRO SIN VIOLENCIA,FUERO COMUN,AGENCIA DE DENUNCIA DIGITAL,CEN-A,UI-1SD,SANTA MARIA NONOALCO,Santa Maria Nonoalco,BENITO JUAREZ,NaN,CDMX,19.384536,-99.186575,OTRAS
209871,2025,Enero,2025-01-21 23:51:01,23:51:01:00,2022.0,Enero,2022-01-01 12:00:00,12:00:00:00,DESPOJO,FUERO COMUN,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN COYOACÁN,COY-1,UI-2CD,ROMERO DE TERREROS,Romero De Terreros,COYOACAN,NaN,CDMX,19.343661,-99.168056,delito de bajo impacto
209872,2025,Enero,2025-01-13 19:15:52,19:15:52:00,2025.0,Enero,2025-01-09 04:30:00,04:30:00:00,ROBO A TRANSEUNTE EN VIA PUBLICA SIN VIOLENCIA,FUERO COMUN,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN ALVAR...,UAT-AO-4,UI-1SD,LORETO,Barrio La Otra Banda,ALVARO OBREGON,NaN,CDMX,19.336988,-99.195002,robo a transeunte en via publica con y sin vio...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209873 entries, 0 to 209872
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   anio_inicio           209873 non-null  int64
 1   mes_inicio            209873 non-null  object
 2   fecha_inicio          209872 non-null  object
 3   hora_inicio           209871 non-null  object
 4   anio_hecho            209819 non-null  float64
 5   mes_hecho             209819 non-null  object
 6   fecha_hecho           209819 non-null  object
 7   hora_hecho            209780 non-null  object
 8   delito                209873 non-null  object
 9   competencia           103445 non-null  object
 10  fiscalia              209873 non-null  object
 11  agencia               209873 non-null  object
 12  unidad_investigacion  209784 non-null  object
 13  colonia_hecho         199622 non-null  object
 14  colonia_catalogo      197385 non-null  object
 15  alcaldia_hecho        207301 non-null  object
 16  alcaldia_catalogo     1748 non-null    object
 17  municipio_hecho       209873 non-null  object
 18  latitud               199714 non-null  float64
 19  longitud              199714 non-null  float64
 20  categoria_delito      209873 non-null  object
dtypes: float64(3), int64(1), object(17)
memory usage: 33.6+ MB

# **4. LIMPIEZA Y NORMALIZACIÓN DE DATOS**

In [ ]:
df = myUtils.apply_dtypes(df, verbose=True) #Usamos verbose para imprimir el procesamiento hecho

Columnas esperadas totales: 21
No faltan columnas esperadas.

Resumen de casting:
• A string: 15 columnas → ['delito', 'categoria_delito', 'competencia', 'fiscalia', 'agencia', 'unidad_investigacion', 'colonia_hecho', 'colonia_catalogo', 'alcaldia_hecho', 'alcaldia_catalogo', 'municipio_hecho', 'hora_inicio', 'hora_hecho', 'mes_inicio', 'mes_hecho']
• A Int64: ['anio_inicio', 'anio_hecho']
• A Float64: ['latitud', 'longitud']
• A datetime64[ns]: ['fecha_inicio', 'fecha_hecho']
   - 'fecha_inicio': no nulos antes = 209872, NaT después = 129812
   - 'fecha_hecho': no nulos antes = 209819, NaT después = 127987

In [ ]:

df = myUtils.normalize_text(df, "delito")
df = myUtils.normalize_text(df, "categoria_delito")
df = myUtils.normalize_text(df, "competencia")
df = myUtils.normalize_months(df, "mes_inicio")
df = myUtils.normalize_months(df, "mes_hecho")
df = myUtils.drop_missing_rows(df, cols_required=["anio_inicio", "mes_inicio", "latitud", "longitud"])
df

Filas eliminadas por nulos en columnas críticas: 10159 de 209873 (4.84%)

,anio_inicio,mes_inicio,fecha_inicio,hora_inicio,anio_hecho,mes_hecho,fecha_hecho,hora_hecho,delito,competencia,fiscalia,agencia,unidad_investigacion,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho,latitud,longitud,categoria_delito
0,2016,Mayo,2016-10-05,00:00:00,2016,Abril,2016-03-04,12:28:00,amenazas,<na>,INVESTIGACIÓN EN COYOACÁN,COY-1,UI-1CD,CULHUACÁN CTM SECCIÓN V,Culhuacan Ctm Seccion I,COYOACAN,<NA>,CDMX,19.33182,-99.11862,delito de bajo impacto
1,2016,Mayo,NaT,00:00:00,2016,Mayo,NaT,15:10:00,lesiones culposas por transito vehicular en co...,<na>,INVESTIGACIÓN EN CUAUHTEMOC,CUH-2,UI-3CD,DOCTORES,Doctores,CUAUHTEMOC,<NA>,CDMX,19.4248,-99.14254,delito de bajo impacto
2,2016,Julio,2016-07-07,00:00:00,2016,Mayo,NaT,02:00:00,robo de objetos,<na>,INVESTIGACIÓN EN CUAUHTEMOC,CUH-2,UI-2SD,SANTA MARIA LA RIBERA,Santa Maria La Ribera,CUAUHTEMOC,<NA>,CDMX,19.44337,-99.15801,delito de bajo impacto
3,2016,Enero,2016-04-01,00:00:00,2016,Enero,2016-04-01,15:30:00,perdida de la vida por otras causas,<na>,INVESTIGACIÓN EN CUAUHTEMOC,CUH-8,UI-3CD,ESPERANZA,Esperanza,CUAUHTEMOC,<NA>,CDMX,19.42177,-99.12674,hecho no delictivo
4,2016,Febrero,2016-08-02,00:00:00,2016,Febrero,2016-01-02,14:00:00,violencia familiar,<na>,INVESTIGACIÓN EN XOCHIMILCO,XO-2,UI-2SD,LA JOYA,<NA>,XOCHIMILCO,<NA>,CDMX,19.231226,-99.095951,delito de bajo impacto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209868,2025,Enero,NaT,16:25:45:00,2025,Enero,NaT,14:00:00:00,violencia familiar,fuero comun,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN TLALPAN,UAT-TLP-5,UI-1SD,PEDREGAL DE AMINCO,Pueblo San Francisco Tlalnepantla,TLALPAN,<NA>,CDMX,19.201846,-99.131102,delito de bajo impacto
209869,2025,Enero,NaT,17:56:48:00,2025,Enero,NaT,14:58:00:00,violencia familiar,fuero comun,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN TLALPAN,TLP-3,UI-1CD,SAN MIGUEL TOPILEJO,Pueblo San Miguel Topilejo,TLALPAN,<NA>,CDMX,19.191853,-99.141353,delito de bajo impacto
209870,2025,Enero,NaT,02:13:04:00,2024,Diciembre,NaT,06:00:00:00,robo a pasajero a bordo de metro sin violencia,fuero comun,AGENCIA DE DENUNCIA DIGITAL,CEN-A,UI-1SD,SANTA MARIA NONOALCO,Santa Maria Nonoalco,BENITO JUAREZ,<NA>,CDMX,19.384536,-99.186575,otras
209871,2025,Enero,NaT,23:51:01:00,2022,Enero,NaT,12:00:00:00,despojo,fuero comun,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN COYOACÁN,COY-1,UI-2CD,ROMERO DE TERREROS,Romero De Terreros,COYOACAN,<NA>,CDMX,19.343661,-99.168056,delito de bajo impacto
209872,2025,Enero,NaT,19:15:52:00,2025,Enero,NaT,04:30:00:00,robo a transeunte en via publica sin violencia,fuero comun,FISCALÍA DE INVESTIGACIÓN TERRITORIAL EN ALVAR...,UAT-AO-4,UI-1SD,LORETO,Barrio La Otra Banda,ALVARO OBREGON,<NA>,CDMX,19.336988,-99.195002,robo a transeunte en via publica con y sin vio...

#**5. DIVISIÓN DE DATOS**

Principio fundamental:

*Todas las transformaciones que aprenden algo de los datos deben hacerse después de dividir entre entrenamiento y prueba.*

Es decir:

1. Primero divides tu dataset → train, test (y opcionalmente val).

2. Luego ajustas (fit) tus transformaciones (feature vectors y/o embeddings) solo con el conjunto de entrenamiento.

3. Finalmente aplicas esas mismas transformaciones (ya ajustadas) a test y val.

Si no se sigue ese orden incurriremos en el problema llamado **DATA LEAKAGE**.

El **data leakage** ocurre cuando información del conjunto de prueba (datos de test) influye, aunque sea indirectamente, en la construcción del modelo o sus features.

Por ejemplo:

| Transformación                        | Si la haces antes de dividir...                   | Resultado                                                |
| ------------------------------------- | ------------------------------------------------- | -------------------------------------------------------- |
| `StandardScaler` o `MinMaxScaler`     | Aprende la media/desviación de todo el dataset    | El modelo ya “conoce” el rango del test → leakage        |
| `OneHotEncoder` con `fit` global      | Aprende todas las categorías del dataset completo | El test influye en la codificación                       |
| `Target encoding`                     | Usa promedios globales de la variable objetivo    | Mezcla info del test en el entrenamiento                 |
| `Feature selection` con `SelectKBest` | Calcula correlaciones sobre todo el dataset       | El modelo ya sabe qué features son relevantes según test |


Entonces, **SIEMPRE** se debe realizar primero la división de datos antes de hacer la construcción de los vectores de características.

In [ ]:
# Definir variables predictoras (X) y objetivo (y)
X = df.drop(columns=["categoria_delito"])  # todas las columnas menos la clase
y = df["categoria_delito"]                 # variable objetivo

In [ ]:
# División estratificada
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,          # 20% para prueba
    random_state=SEED,         # reproducibilidad
    stratify=y               # mantiene la proporción de categorías de delito
)

In [ ]:
# Confirmar tamaños y proporciones
print("División completada:")
print(f"   - Entrenamiento: {X_train.shape[0]:,} filas ({100 * X_train.shape[0] / df.shape[0]:.2f}%)")
print(f"   - Prueba:        {X_test.shape[0]:,} filas ({100 * X_test.shape[0] / df.shape[0]:.2f}%)")

# Verificación rápida de balance de clases
print("\nDistribución de clases (train vs test):")
print("Train:")
print(y_train.value_counts(normalize=True).round(3))
print("\nTest:")
print(y_test.value_counts(normalize=True).round(3))

División completada:
   - Entrenamiento: 159,771 filas (80.00%)
   - Prueba:        39,943 filas (20.00%)

Distribución de clases (train vs test):
Train:
categoria_delito
delito de bajo impacto                                  0.823
robo a transeunte en via publica con y sin violencia    0.051
robo de vehiculo con y sin violencia                    0.043
otras                                                   0.037
hecho no delictivo                                      0.032
robo a negocio con violencia                            0.014
Name: proportion, dtype: float64

Test:
categoria_delito
delito de bajo impacto                                  0.823
robo a transeunte en via publica con y sin violencia    0.051
robo de vehiculo con y sin violencia                    0.043
otras                                                   0.037
hecho no delictivo                                      0.032
robo a negocio con violencia                            0.014
Name: proportion, dtype: float64

In [ ]:
# GUARDAR ENTRENAMIENTO y PRUEBA

# Combinar X e y para guardar juntos
train_df = X_train.copy()
train_df["categoria_delito"] = y_train

test_df = X_test.copy()
test_df["categoria_delito"] = y_test


# Rutas de guardado
DATA_DIR = os.path.join(BASE_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True) # Crear el directorio si no existe

train_path = os.path.join(DATA_DIR, "train_split.csv")
test_path = os.path.join(DATA_DIR, "test_split.csv")
y_train_path = os.path.join(DATA_DIR, "y_train.csv")
y_test_path = os.path.join(DATA_DIR, "y_test.csv")



# Guardar a CSV (UTF-8 con BOM para compatibilidad)
train_df.to_csv(train_path, index=False, encoding="utf-8-sig")
test_df.to_csv(test_path, index=False, encoding="utf-8-sig")
y_train.to_csv(y_train_path, index=False, encoding="utf-8-sig")
y_test.to_csv(y_test_path, index=False, encoding="utf-8-sig")


# Confirmación
print("\n Archivos guardados correctamente:")
print(f"   - Entrenamiento: {train_path}")
print(f"   - Prueba:        {test_path}")
print(f"   - y_train separado:        {y_train_path}")
print(f"   - y_test separado:         {y_test_path}")


# Verificación opcional de balance de clases
print("\nDistribución de clases (train vs test):")
print("Train:")
print(y_train.value_counts(normalize=True).round(3))
print("\nTest:")
print(y_test.value_counts(normalize=True).round(3))

 Archivos guardados correctamente:
   - Entrenamiento: /drive/My Drive/Colab Notebooks/reto-Thales/data/train_split.csv
   - Prueba:        /drive/My Drive/Colab Notebooks/reto-Thales/data/test_split.csv
   - y_train separado:        /drive/My Drive/Colab Notebooks/reto-Thales/data/y_train.csv
   - y_test separado:         /drive/My Drive/Colab Notebooks/reto-Thales/data/y_test.csv

Distribución de clases (train vs test):
Train:
categoria_delito
delito de bajo impacto                                  0.823
robo a transeunte en via publica con y sin violencia    0.051
robo de vehiculo con y sin violencia                    0.043
otras                                                   0.037
hecho no delictivo                                      0.032
robo a negocio con violencia                            0.014
Name: proportion, dtype: float64

Test:
categoria_delito
delito de bajo impacto                                  0.823
robo a transeunte en via publica con y sin violencia    0.051
robo de vehiculo con y sin violencia                    0.043
otras                                                   0.037
hecho no delictivo                                      0.032
robo a negocio con violencia                            0.014
Name: proportion, dtype: float64