In [ ]:
numeric_features = data.select_dtypes(include=['int', 'float']).columns.tolist() # get numeric feature names
print("Numeric features:", numeric_features) # print numeric feature names

text_features = data.select_dtypes(include="string").columns.tolist() # get text feature names
print("Text features:", text_features) # print text feature names

Numeric features: ['anio_inicio', 'anio_hecho', 'latitud', 'longitud']
Text features: ['mes_inicio', 'fecha_inicio', 'hora_inicio', 'mes_hecho', 'fecha_hecho', 'hora_hecho', 'delito', 'categoria_delito', 'competencia', 'fiscalia', 'agencia', 'unidad_investigacion', 'colonia_hecho', 'colonia_catalogo', 'alcaldia_hecho', 'alcaldia_catalogo', 'municipio_hecho']

In [ ]:
# Describe the statistics of the data (only numeric columns)
data.describe()

       anio_inicio   anio_hecho      latitud     longitud
count 2,098,743.00 2,098,184.00 1,997,536.00 1,997,536.00
mean      2,020.10     2,019.94        19.39       -99.14
std           2.58         3.07         0.07         0.06
min       2,016.00       222.00        19.10      -100.23
25%       2,018.00     2,018.00        19.34       -99.18
50%       2,020.00     2,020.00        19.39       -99.14
75%       2,022.00     2,022.00        19.44       -99.10
max       2,025.00     2,025.00        19.58       -98.95

In [ ]:
data[text_features].describe() # describe only the string columns

,mes_inicio,fecha_inicio,hora_inicio,mes_hecho,fecha_hecho,hora_hecho,delito,categoria_delito,competencia,fiscalia,agencia,unidad_investigacion,colonia_hecho,colonia_catalogo,alcaldia_hecho,alcaldia_catalogo,municipio_hecho
count,2098743,2098740,2098728,2098184,2098183,2097856,2098743,2098743,1034725,2098741,2098743,2097765,1996619,1974303,2073847,17586,2098743
unique,19,56540,115107,19,32513,2872,357,18,3,100,230,158,1699,1423,17,1,1
top,Octubre,2020-03-06,00:00:00,Enero,2021-01-01,12:00:00,VIOLENCIA FAMILIAR,DELITO DE BAJO IMPACTO,FUERO COMUN,AGENCIA DE DENUNCIA DIGITAL,CEN-1,UI-1SD,CENTRO,Centro,CUAUHTEMOC,CDMX (indeterminada),CDMX
freq,185141,934,1484811,183889,1259,192234,261181,1711755,1000272,150858,72170,737376,65086,65266,318787,17586,2098743